name: 'p2 GitHub Scheduler'
description: 'Reschedule GitHub Issues using p2 scheduling algorithm'
author: 'OctoberSwimmer'
branding:
  color: blue
  icon: calendar

inputs:
  token-broker-url:
    description: 'URL of the p2-penny-pusher token broker'
    required: false
    default: 'https://penny-pusher.octoberswimmer.com'
  github-url:
    description: 'GitHub URL to schedule (project, repo, or issue URL). Auto-detected from issue event if not provided.'
    required: false
  dry-run:
    description: 'Show changes without applying them'
    required: false
    default: 'false'
  timezone:
    description: 'Timezone for scheduling (e.g. America/New_York, Europe/London). Defaults to UTC.'
    required: false
    default: 'UTC'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  version:
    description: 'Release tag of p2-github-scheduler to install (e.g. v1.0.0). Use "latest" to resolve dynamically.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Resolve release tag
      id: resolve
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -euo pipefail
        action_repo="${{ github.action_repository }}"
        if [[ -z "${action_repo}" ]]; then
          action_repo="octoberswimmer/p2-github-scheduler"
        fi
        go run ./cmd/actions/resolve \
          --requested "${{ inputs.version }}" \
          --repo "${action_repo}" \
          --fallback "${{ github.repository }}"

    - name: Install p2-github-scheduler
      id: install
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        ACTION_REPO: ${{ steps.resolve.outputs.repo }}
        VERSION: ${{ steps.resolve.outputs.version }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
        RUNNER_TEMP: ${{ runner.temp }}
      run: |
        set -euo pipefail
        dest="${RUNNER_TEMP}/p2-github-scheduler"
        go run ./cmd/actions/install \
          --repo "${ACTION_REPO}" \
          --version "${VERSION}" \
          --runner-os "${RUNNER_OS}" \
          --runner-arch "${RUNNER_ARCH}" \
          --dest "${dest}"

    - name: Get installation token
      id: token
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        go run ./cmd/actions/token --broker-url "${{ inputs.token-broker-url }}"

    - name: Run scheduler
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        TZ: ${{ inputs.timezone }}
      run: |
        GITHUB_URL="${{ inputs.github-url }}"
        if [ -z "$GITHUB_URL" ]; then
          # Auto-detect from issue event, or fall back to repository
          if [ -n "${{ github.event.issue.number }}" ]; then
            GITHUB_URL="https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          else
            GITHUB_URL="https://github.com/${{ github.repository }}"
          fi
        fi

        echo "Scheduling: $GITHUB_URL"

        ARGS=""
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          ARGS="$ARGS --dry-run"
        fi
        if [ "${{ inputs.debug }}" = "true" ]; then
          ARGS="$ARGS --debug"
        fi

        p2-github-scheduler $ARGS "$GITHUB_URL"
